controllers/IndexController.php
<?php
namespace app\controllers;
use Yii;
use app\models\Questionnaire;
use app\models\Manager;
use yii\web\Controller;
use yii\data\Pagination;
use moonland\phpexcel\Excel;

class IndexController extends Controller{
    public $layout = false;
    
    public function validate(){
        if(Yii::$app->session["admin"]["isLogin"]!="808"){
            Yii::$app->session->setFlash('info','[TimeOut]Please Login!!');
            return $this->redirect(["index/login"]);
        } else {
            return true;
        }
    }
    
    public function actionLogin(){
        $model = new Manager();
        if(Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
            if($model->login($post)){
                Yii::$app->session->setFlash('info','Login success');
                return $this->redirect(["index/manage"]);
            } else {
                Yii::$app->session->setFlash('info','Login error');
                return $this->render("login",["model"=>$model]);
            }
        }
        return $this->render("login",["model"=>$model]);
    }

    public function actionQuestionnaire(){
        $model = new Questionnaire();
        if(Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
            if($model->submit($post)){
                Yii::$app->session->setFlash("info","Submit success");
                return $this->redirect(["index/questionnaire"]);
            }else{
                Yii::$app->session->setFlash("info","Submit error,Code/ID was blank!");
                return $this->render("show",["post"=>$post]);
            }
        }
        return $this->render("table",["model" => $model]);
    }

    public function actionManage(){
        $this->validate();
        $model = Questionnaire::find()->orderBy(["Code"=>SORT_ASC]);
        $count = $model->count();
        $pager = new Pagination(['totalCount' => $count, 'pageSize' => 100]);
        $lists = $model->offset($pager->offset)->limit($pager->limit)->all();
        return $this->render("manager", ['lists' => $lists, 'pager' => $pager]);
    }
    
    public function actionSearch(){
        $this->validate();
        if(Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
        } else {
            $this->actionManage();
        }
        $model = Questionnaire::find()->where("Code = :Code or ID = :ID",[":Code"=>$post["search"],":ID"=>$post["search"]])->orderBy(["Code"=>SORT_ASC]);
        $count = $model->count();
        $pager = new Pagination(['totalCount' => $count, 'pageSize' => 10]);
        $lists = $model->offset($pager->offset)->limit($pager->limit)->all();
        return $this->render("manager", ['lists' => $lists, 'pager' => $pager]);
    }
    
    public function actionChangepass(){
        $this->validate();
        $model = new Manager();
        if(Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
            if($model->change($post)){
                Yii::$app->session->setFlash('info','Change successfully');
                Yii::$app->session["admin"]=[
                    "isLogin"=>"0"
                ];
                return $this->redirect(["index/login"]);
            } else {
                Yii::$app->session->setFlash('info','Change false');
            }
        }
        return $this->render("changepass",['model'=>$model]);
    }
    
    public function actionExport(){
        $this->validate();
        $model = Questionnaire::find()->orderBy(["Code"=>SORT_ASC]);
        $data = $model->all();
        Excel::export([
            'models'=>$data,
            'format'=>'Excel5',
            'fileName'=>  date("d-m-Y H:i:s"),
            'columns'=>[

                "Code",
                "ID",

                "OSA__Study_notes",
                "OSA__Study_involvement",
                "OSA__Diagnosis_Date",
                "OSA__ESS",
                "OSA__RDI",
                "OSA__TST",
                "OSA__Eff",
                "OSA__CPAP_titration",
                "OSA__CPAP_pressure",
                "OSA__CPAP_Compliance",
                "OSA__OA",
                "OSA__OA_compliance",
                "OSA__Others",

                "HTN__HTN",
                "HTN__Diagnosis_Date",
                "HTN__Medication",
                "HTN__Num_of_Antihypertensive_Agents",
                "HTN__Med1",
                "HTN__Med2",
                "HTN__Med3",
                "HTN__Med4",
                "HTN__Med5",
                "HTN__Notes",

                "DM__DM",
                "DM__IGT",
                "DM__IFG",
                "DM__Diagnosis_Date",
                "DM__Notes",

                "Hyperlipidaemia__Lipid",
                "Hyperlipidaemia__Diagnosis_Date",
                "Hyperlipidaemia__Med",
                "Hyperlipidaemia__Date_of_treatment",
                "Hyperlipidaemia__Notes",

                "NAFLD__NAFLD",
                "NAFLD__Diagnosis_Date",
                "NAFLD__Notes",

                "Metabolic_syndrome__MS",
                "Metabolic_syndrome__Diagnosis_Date",
                "Metabolic_syndrome__Notes",

                "Dysrrhythmias__Dysrrhythmias",
                "Dysrrhythmias__Atrial_fibrillation",
                "Dysrrhythmias__Diagnosis_Date",
                "Dysrrhythmias__Notes",

                "IHD__IHD",
                "IHD__AMI",
                "IHD__STEMI",
                "IHD__NSTEMI",
                "IHD__Diagnosis_Date",
                "IHD__Unstable_angina",
                "IHD__CABG",
                "IHD__PCI",
                "IHD__Date_of_intervention",
                "IHD__Notes",

                "Cardiomypathy__Cardiomypathy",
                "Cardiomypathy__Diagnosis_Date",
                "Cardiomypathy__Notes",

                "CHF__CHF",
                "CHF__LVEF",
                "CHF__Diagnosis_Date",
                "CHF__Notes",

                "Cor_pulmonale__Cor_pulmonale",
                "Cor_pulmonale__Diagnosis_Date",
                "Cor_pulmonale__Notes",

                "Carotid_Artery_Stenosis__Stenosis",
                "Carotid_Artery_Stenosis__Diagnosis_Date",
                "Carotid_Artery_Stenosis__Notes",

                "Stroke__Stroke",
                "Stroke__ICH",
                "Stroke__Cerebral_infarction",
                "Stroke__TIA",
                "Stroke__Diagnosis_Date",
                "Stroke__Notes",

                "Cancer__Cancer",
                "Cancer__Diagnosis",
                "Cancer__Pathology",
                "Cancer__Diagnosis_Date",
                "Cancer__Notes",

                "Mental_disorder__Mental_disorder",
                "Mental_disorder__Diagnosis",
                "Mental_disorder__Diagnosis_Date",
                "Mental_disorder__Notes",

                "COPD__COPD",
                "COPD__GOLD_Stage",
                "COPD__Diagnosis_Date",
                "COPD__Notes",

                "Blood_test__Test_date1",
                "Blood_test__Chol",
                "Blood_test__LDL",
                "Blood_test__HDL",
                "Blood_test__Trigl",
                "Blood_test__Test_date2",
                "Blood_test__HbA1c",
                "Blood_test__FS",

                "Mortality__Death",
                "Mortality__Direct_cause",
                "Mortality__Antecedent_causes",
                "Mortality__Date_of_death",

                "OSA_related_disease__OSA_related_disease",

                "Censering_date",
                "Collecting_date",

            ],
        'headers'=>[

            "Code"=>"Code",
            "ID"=>"ID",

            "OSA__Study_notes"=>"Study notes",
            "OSA__Study_involvement"=>"Study involvement",
            "OSA__Diagnosis_Date"=>"Diagnosis Date",
            "OSA__ESS"=>"ESS",
            "OSA__RDI"=>"RDI",
            "OSA__TST"=>"TST",
            "OSA__Eff"=>"Eff%",
            "OSA__CPAP_titration"=>"CPAP titration",
            "OSA__CPAP_pressure"=>"CPAP pressure",
            "OSA__CPAP_Comliance"=>"CPAP Compliance",
            "OSA__OA"=>"OA",
            "OSA__OA_compliance"=>"OA compliance",
            "OSA__Others"=>"Others",

            "HTN__HTN"=>"HTN",
            "HTN__Diagnosis_Date"=>"Diagnosis Date",
            "HTN__Medication"=>"Medication",
            "HTN__Num_of_Antihypertensive_Agents"=>"Num. of Antihypertensive Agents",
            "HTN__Med1"=>"Med1",
            "HTN__Med2"=>"Med2",
            "HTN__Med3"=>"Med3",
            "HTN__Med4"=>"Med4",
            "HTN__Med5"=>"Med5",
            "HTN__Notes"=>"Notes",

            "DM__DM"=>"DM",
            "DM__IGT"=>"IGT",
            "DM__IFG"=>"IFG",
            "DM__Diagnosis_Date"=>"Diagnosis Date",
            "DM__Notes"=>"Notes",

            "Hyperlipidaemia__Lipid"=>"Lipid",
            "Hyperlipidaemia__Diagnosis_Date"=>"Diagnosis Date",
            "Hyperlipidaemia__Med"=>"Med",
            "Hyperlipidaemia__Date_of_treatment"=>"Date of treatment",
            "Hyperlipidaemia__"=>"Notes",

            "NAFLD__NAFLD"=>"NAFLD",
            "NAFLD__Diagnosis_Date"=>"Diagnosis Date",
            "NAFLD__Notes"=>"Notes",

            "Metabolic_syndrome__MS"=>"MS",
            "Metabolic_syndrome__Diagnosis_Date"=>"Diagnosis Date",
            "Metabolic_syndrome__Notes"=>"Notes",

            "Dysrrhythmias__Dysrrhythmias"=>"Dysrrhythmias",
            "Dysrrhythmias__Atrial_fibrillation"=>"Atrial fibrillation",
            "Dysrrhythmias__Diagnosis_Date"=>"Diagnosis Date",
            "Dysrrhythmias__Notes"=>"Notes",

            "IHD__IHD"=>"IHD",
            "IHD__AMI"=>"AMI",

views/index/changepass.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers;
?>
<style>
        *{
                font-family: 微软雅黑;
        }
        input{
                background-color: white;
                border: 2px solid #333;
                text-align: center;
        }
        tr>td:first-child{
                width:180px;
                text-align: center;
        }
        tr>td:last-child{
                text-align: center;
        }
        .btn:hover{
                background-color: #999;
        }
</style>
<body style="background-color: #666;">
<div style="margin: 0 auto;border: 2px solid #333;width: 500px;padding: 15px;background-color: white;height: 200px;box-shadow: -13px 13px #333;margin-top: 150px;">
<?php $form = ActiveForm::begin(["fieldConfig"=>["template"=>"{error}{input}"]])?>
<table align="center">
<tr>
<th colspan="2"><h1>Change Password</h1></th>
</tr>
<tr>
<td>OldPass:</td>
<td><?= $form->field($model,"OldPass")->passwordInput()?></td>
</tr>
<tr>
<td>NewPass:</td>
<td><?= $form->field($model, "NewPass")->passwordInput()?></td>
</tr>
<tr>
<td>NewPass-again:</td>
<td><?= $form->field($model, "RePass")->passwordInput()?></td>
</tr>
<tr>
<td><br><input class="btn" type="submit" value="Change"></td>
<td><br><input class="btn" type="reset" value="Reset"></td>
</tr>
</table>
<?php ActiveForm::end()?>
</div>
<footer>
<p style="color: white;position: fixed;bottom: 0px;">Version0.7--Build in 01/18/2017</p>
</footer>
<script>
    <?php if(Yii::$app->session->hasFlash("info")){
        echo "alert("."'".Yii::$app->session->getFlash("info")."'".")";
    }?>
</script>
</body>

views/index/login.php
<?php
$this->title = "Login";
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<style>
        *{
                font-family: 微软雅黑;
        }
        input{
                background-color: white;
                border: 2px solid #333;
                text-align: center;
                font-size: 16px;
        }
        tr>td:first-child{
                width:180px;
                text-align: center;
        }
        tr>td:last-child{
                text-align: center;
        }
        .btn:hover{
                background-color: #999;
        }
</style>
<body style="background-color: #666;">
<div style="margin: 0 auto;border: 2px solid #333;width: 500px;padding: 15px;background-color: white;height: 200px;box-shadow: -13px 13px #333;margin-top: 150px;">
<?php $form = ActiveForm::begin(["fieldConfig"=>["template"=>"{error}{input}"]])?>
<table align="center">
<tr>
<th colspan="2"><h1>Q system</h1></th>
</tr>
<tr>
<td>Admin:</td>
<td><?= $form->field($model, "admin")->textInput()?></td>
</tr>
<tr>
<td>Password:</td>
<td><?= $form->field($model, "password")->passwordInput()?></td>
</tr>
<tr>
<td><br><input type="submit" value="Login" class="btn"></td>
<td><br><input type="reset" value="Reset" class="btn"></td>
</tr>
</table>
<?php ActiveForm::end()?>
</div>
<footer>
<p style="color: white;position: fixed;bottom: 0px;">Version0.7--Build in 01/18/2017</p>
</footer>
<script>
    <?php if(Yii::$app->session->hasFlash("info")){
        echo "alert("."'".Yii::$app->session->getFlash("info")."'".")";
    }?>
</script>
</body>

views/index/manager.php
<?php
    use yii\helpers;
    use yii\widgets\ActiveForm;
?>
<style>
        *{
                font-family: 微软雅黑;
        }
        body{
                background-color: #666;
        }
        .Search{
                width: 405px;
                border: 2px solid #333;
                background-color: white;
                font-size: 20px;
                text-align: center;
        }
        .btn{
                width: 200px;
                border: 2px solid #333;
                background-color: white;
                font-size: 20px;
        }
        .btn:hover{
                background-color: #999;
        }
        .lists tr>th{
            width: 200px;
        }
        .lists{
            text-align: center;
            border:skyblue;
        }
        .lists tr:hover{
            background-color: #999;
        }
        .page_style .active a{
            background-color: #222;
            color: white;
        }
        .pagination{
            text-align: center;
        }
        .pagination li{
            list-style: none;
            display: inline;
            font-size: 18px;
        }
        .pagination a{
            text-decoration: none;
            padding: 5px;
            border: 1px solid #999;
        }
</style>
<body>
<div style="width: 1170px;background-color: white;padding: 15px;margin: 0 auto;box-shadow: -10px 10px #222">
<div style="border: 2px solid #333;padding: 15px;">
<table align="center">
<tr>
<td><a href="<?php echo helpers\Url::to(['index/questionnaire']);?>" target="_blank"><button class="btn">Add Questionnaire</button></a></td>
<td><a href="<?php echo helpers\Url::to(['index/manage']);?>"><button class="btn">Show All</button></a></td>
<td><a href="<?php echo helpers\Url::to(['index/export']);?>"><button class="btn">Export Excel</button></a></td>
<td><a href="<?php echo helpers\Url::to(['index/changepass']);?>"><button class="btn">Change Pass</button></a></td>
<td><a href="<?php echo helpers\Url::to(['index/logout']);?>"><button class="btn">Logout</button></a></td>
</tr>
<tr>
<td></td>
<td colspan="3">
    <form action="<?php echo helpers\Url::to(["index/search"]);?>" method="post">
    <input class="Search" type="text" name="search" placeholder="Code/ID">
    <input type="hidden"
    name="<?= \Yii::$app->request->csrfParam; ?>"
    value="<?= \Yii::$app->request->getCsrfToken();?>">
    <input class="btn" type="submit" value="Search"></form>
    </td>
</tr>
</table>
<div style="background-color: #B8CCE4">
<table class="lists" align="center" cellspacing="0"  border="1px solid">
<tr>
<th>NUM.</th>
<th>Code</th>
<th>ID</th>
<th>CollectTime</th>
<th colspan="3">Operate</th>
</tr>
<?php $i=1; foreach ($lists as $list):?>
<tr>
<td><?= $i++;?></td>
<td><?= $list['Code'];?></td>
<td><?= $list['ID'];?></td>
<td><?= $list['Collecting_date'];?></td>
<td><a class="view" href="<?= helpers\Url::to(["index/view",["Code"=>$list['Code']]]);?>">View</a></td>
<td><a class="edit" href="<?= helpers\Url::to(["index/edit",["Code"=>$list['Code']]]);?>">Edit</a></td>
<td><a class="del" href="<?= helpers\Url::to(["index/del",["Code"=>$list['Code']]]);?>" onclick="return confirm('[Warning]Can`t recovery after delete')">Del</a></td>
</tr>
<?php endforeach;?>
</table>
</div>
</div>
    <div class="pagination page_style">
    <?php echo yii\widgets\LinkPager::widget(['pagination' => $pager, 'prevPageLabel' => '&#8249;', 'nextPageLabel' => '&#8250;']); ?>
</div>
</div>
</body>
<script>
    <?php if(Yii::$app->session->hasFlash("info")){
        echo "alert("."'".Yii::$app->session->getFlash("info")."'".")";
    }?>
</script>

views/index/show.php
<h1>页面错误提示-------harikisei@live.com</h1>
<?php
echo "<pre style='font-size:18px'>";
echo $post;
echo "</pre>";
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */